name: Auto deploy to NCP
run-name: Running
on:
  push:
    branches:
      - main
      - feature/build-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 체크아웃 및 JDK 세팅
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # YML 파일 생성
      - name: Setting secret
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.SECRET_YML }}" > ./src/main/resources/application.yml
          find src
        shell: bash

      # Gradle 권한 부여
      - name: Grant permission for gradlew
        run: chmod +x ./gradlew

      # 테스트 및 빌드
      - name: Build with Gradle
        run: ./gradlew clean build

      #빌드한 jar 파일을 도커 이미지로 빌드하고 도커 허브에 푸시
      - name: docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --no-cache -t ${{ secrets.DOCKER_REPO }}:test .
          docker push ${{ secrets.DOCKER_REPO }}:test